erDiagram
    NOTICES }o--|{ SOURCE : hasNotice
    CONCEPT }o--o{ SOURCE : hasConcept
    QUESTION }o--|{ SOURCE : hasQuestion

    CONCEPT }o--o{ CONCEPT : "Broader or Narrower or related"

    CONCEPT }o--|| INTERNATIONALISATION : hasInternationalisation

    SOURCE {
        string id
        string description
        string value
    }

    NOTICES {
        string id
        string name
    }

    QUESTION {
        string id
        string name
    }

    CONCEPT {
        string id
        string description
        string ark
        string name
        string note
        string definition
    }
    INTERNATIONALISATION {
        string id
        string value
        string lang
    }